name: PR
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        target:
          - test-debian
          - test-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          make ${{ matrix.target }}
          make clean
